module rate_constants_utility 

use ccpp_kinds, only: r8 => kind_phys 

! This code was generated by Preprocessor revision 2faf7d29a380d235f4972fa72d64f10108c1f98c
! Preprocessor source https://github.com/NCAR/MechanismToCode

! This code is generated from tag 265 of the mechanism, Chapman.  It is named Minimal_Chapman
! This tag was created on 2019-07-24 11:21:46.789289-06 by ajc and is marked as not buggy

  implicit none

  public :: p_rate_mapping,  k_rate_constant 

  contains

subroutine p_rate_mapping(tuv_rates, j_rate_const)
    real(KIND=r8),           intent(in)  :: tuv_rates(:) ! /sec 
    real(KIND=r8),           intent(out) :: j_rate_const(:) ! /sec 
    j_rate_const(1) = tuv_rates(1) 
    j_rate_const(2) = tuv_rates(2) 
    j_rate_const(3) = tuv_rates(3) 
end subroutine p_rate_mapping 

subroutine k_rate_constant(k_rate_constants, number_density_air, TEMP)
    real(KIND=r8),           intent(in)  :: TEMP ! temperature
    real(KIND=r8),           intent(in)  :: number_density_air ! P/kT molecules/cm3 
    real(KIND=r8),           intent(out) :: k_rate_constants(:) ! rate constant for the each reaction
    real(KIND=r8):: t_inv, t_inv_300 ! 1/T, 300/T 
    real(KIND=r8):: c_m ! number density 
    c_m = number_density_air 
    t_inv = 1 / TEMP 
    t_inv_300 = 300 / TEMP 
    k_rate_constants(1) = arrhenius(2.15e-11_r8, -110._r8, t_inv) 
    k_rate_constants(2) = arrhenius(3.3e-11_r8, -55._r8, t_inv) 
    k_rate_constants(3) = arrhenius(8e-12_r8, 2060._r8, t_inv) 
    k_rate_constants(4) = low_pressure_termolecular(6.00e-34_r8, 2.4_r8, t_inv_300) 
end subroutine k_rate_constant 



REAL(KIND=r8) FUNCTION arrhenius( A, E_over_R, t_inv )

    REAL(KIND=r8), INTENT(IN) :: A                       ! 
    REAL(KIND=r8), INTENT(IN) :: E_over_R           !
    REAL(KIND=r8), INTENT(IN) ::  t_inv                 ! inverse of temperature

    arrhenius = A * exp ( - E_over_R * t_inv )

end function arrhenius

REAL(KIND=r8) FUNCTION low_pressure_termolecular(A, eTemp, t_inv_300 )
! JPL15-10
    REAL(KIND=r8), INTENT(IN) :: A                       ! coefficient
    REAL(KIND=r8), INTENT(IN) :: eTemp               ! exponential for inverse temperature
    REAL(KIND=r8), INTENT(IN) :: t_inv_300          ! 300 K / temperature (K)

    low_pressure_termolecular = A * t_inv_300**eTemp

end function low_pressure_termolecular


end module rate_constants_utility

